### ISSUE TITLE
lower case variables doesn't work, only all upper case would work

### ISSUE THREAD

**Issue by yizongk** [jakubroztocil/django-settings-export#10]
I am not sure if this is an issue to begin with, or it's an intended feature, but:

When you declare variables with lower case,
```
server_type = "QA"
SETTINGS_EXPORT = [
    'server_type ',
]
```
And then when you try access it on a template
```
{{ settings.server_type }}
```
it would output the following error message:
"settings.server_type " is included in settings.SETTINGS_EXPORT but it does not exist. 

To fix this, you must use all capitals for your variable name like:
```
SERVER_TYPE = "QA"
SETTINGS_EXPORT = [
    'SERVER_TYPE ',
]
...In Your Template html...
{{ settings.server_type }}
```
This would work.

Is this a bug? or an intended feature?

**Comment by jakubroztocil** [comment]
I believe that Django only considers `UPPERCASE` variables in `settings.py` as settings, so we don’t even see them.
